### ISSUE TITLE
.atomic is not posting data properly

### ISSUE THREAD

**Issue by ghost** [dscape/nano#193]
The post data doesn't show up in form variable on the couchdb server. 
This is what appears on the couchdb server when using atomic function with doc id instead of the example you have in the documentation.

body: '{"username":"a@c.com","id":"user:a@c.com"}',
form: {},

**Comment by PaperElectron** [comment]
Im running into this issue as well. Nano seems to be sending a PUT with data in the body, and it isn't parsing the data into the form parameter. It is looking for key=value data to parse not '{"key":"value"}', which is what it is getting.

In other words, copying the example from the nano docs, doesn't work. The function runs just fine in couch, but the right values aren't populated.

**Comment by dscape** [comment]
@PaperElectron in that case, you can read my comment to see how you can proceed to help me fix it. Without that, consider this a non issue.

**Comment by PaperElectron** [comment]
@dscape I was just confirming the issue for anyone that stumbled on it, I poked around in the nano source a bit and the obvious things (PUT to POST) etc. didn't fix it. I don't have the time to fix it properly at the moment otherwise I would have just fixed it and sent a PR, so all I can do is add some extra info. 

For anyone stumbling into this, JSON.parse(req.body) in the design doc update function works just fine.
