### ISSUE TITLE
Dependency has an active security advisory

### ISSUE THREAD

**Issue by tciuro** [dscape/nano#253]
The current version of nano contains an active security advisory:

    Name  Installed  Patched  Vulnerable Dependency
    qs      0.6.6     >= 1.x  xcsnode@undefined > nano@6.0.2 > follow@0.11.3 > request@2.34.0 > qs@0.6.6

Here's more [info] (http://nodesecurity.io/advisories/qs_dos_extended_event_loop_blocking)

**Comment by tciuro** [comment]
Looks like upgrading to the latest takes care of the problem (request@2.51.1)

**Comment by dscape** [comment]
Thank you,

will review when back from vacation

Nuno

**Comment by jo** [comment]
To update request from current `2.46.0` to suggested `2.51.1` some work needs to be done on the code. At least for `multipart.get`, where some tests are failing.

**Comment by jo** [comment]
The qs vulnerability in request has been [fixed in `2.40.0`](https://github.com/request/request/blob/master/CHANGELOG.md#v2400-20140806) with the [update of qs to 1.0.0](https://github.com/request/request/pull/992).

The problem here is not nanos request dependency but follows request. The current follow `0.11.4` [uses request `2.44.0`](https://github.com/iriscouch/follow/blob/v0.11.4/package.json#L13).

That said we should update follow from `0.11.3` to `0.11.4`.
